### ISSUE TITLE
Please sign commits with your GPG key

### ISSUE THREAD

**Issue by jonathancross** [dalitsairio/coinglacier.org#9]
Hello,
First of all, Nice project!

It would be great if you could begin signing your git commits with your gpg key:
[`12A2 411A 8C5C C035 6DDB  767C 24B0 274E 5B6C A8B1`](https://coinglacier.org/coinglacier-pgp-key.txt).

This would help us build up trust over time that key 0x24B0274E5B6CA8B1 is actually owned by the rightful developer (_proof of commits_ :-)

Would also be great if you could get your key signed by a key in the Open PGP Web Of Trust.

PS: I'm this guy: https://twitter.com/jonf3n/status/1062380032889368576

**Comment by dalitsairio** [comment]
Hi jonf3n

Thanks for your great feedback.
You are right with what you say, I will adjust my PGP related customs.

**Comment by jonathancross** [comment]
Great!  Please let me know if I can help in any way.
I created https://gpg.wtf if you have a "WTF!?" moment with `gpg` (as most of us do eventually :-)
